CREATE TABLE [tvmaze].[Show]
(
	[Key] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Id] INT NOT NULL,
	[Name] VARCHAR(255) NOT NULL,
	[Cast] VARCHAR(MAX) NOT NULL
)
GO
CREATE NONCLUSTERED INDEX [IDX_Show_Id]
    ON [tvmaze].[Show]([Id] ASC) WITH (FILLFACTOR = 85, DATA_COMPRESSION = PAGE);
GO
